name: Create Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: 'test-minecraft-plugin.zip'
          path: '.'
      - name: Deploy Release
        uses: ncipollo/release-action@v1.8.8
        with:
          artifact: 'test-minecraft-plugin.zip'
